[tool.black]
line-length = 79
exclude = '''
(
  /(  # generated files
    .tox|
    venv|
    venv.*|
    .venv.*|
    target.*|
    .*/build/lib/.*|
    exporter/opentelemetry-exporter-zipkin-proto-http/src/opentelemetry/exporter/zipkin/proto/http/v2/gen|
    opentelemetry-proto/src/opentelemetry/proto/.*/.*|
    scripts
  )/
)
'''
[tool.pytest.ini_options]
addopts = "-rs -v"
log_cli = true

[tool.rye]
virtual = true
dev-dependencies = [
    "grpcio-tools>=1.64.0",
    "mypy-protobuf>=3.6.0",
]

[tool.rye.workspace]
members = ["opentelemetry-api", "exporter/*", "opentelemetry-proto", "opentelemetry-sdk",
           "opentelemetry-semantic-conventions", "propagator/*", "shim/*"]

[project]
name = "opentelemetry-python"
version = "0.0.1"
